coverage:
  precision: 2
  round: nearest
  range: "40...70"
  ignore: 
     - "src/main/java/com/example/javamavenjunithelloworld/Hello.java"
     - "src/main/java/com/example/javamavenjunithelloworld/HelloApp.java"